site_name: Zensical Docs 
site_url: https://github.com/vishwanathan-m1/material_to_zensical
docs_dir: source
site_dir: docs
use_directory_urls: false
theme:
  name: material  
# Repository
repo_url: https://github.com/vishwanathan-m1/material_to_zensical
repo_name: vishwanathan-m1/material_to_zensical
edit_uri: ""